# Generated by Django 6.0.7 on 2026-07-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steellearn_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
