# Generated by Django 6.0.7 on 2026-08-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steellearn_ai', '0003_trainingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='role',
            field=models.CharField(choices=[('New Employee', 'New Employee'), ('Technician', 'Technician'), ('Electrician', 'Electrician'), ('Welder', 'Welder'), ('Supervisor', 'Supervisor'), ('HR', 'HR')], default='New Employee', max_length=30),
        ),
    ]
